version: '3.9'

services:

  database:
    image: postgres:15.0
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.root
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    # depends_on:
    #   - database
    ports:
      - 5050:80